language: java
jdk:
  - oraclejdk8
  - openjdk7
env:
  global:
    - secure: Aks/9RTuubSZSP5N3Do7uldJk5tpYLcq4atTzhClhV3LkphFzeOhE5WnL1CrwVhSx8wk8LQi6VQcmSt0ayjH1Vi7oABmfWv7YfI6wUaHBmCnb/vTE/ixoxVi5Px3QlOOaKj/xdmgHq/TV97PmGQ4bFU95uBpA+6sQfvf7qw3wLE=
addons:
  chrome: stable
before_install:
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - export PATH=$PATH:/usr/lib/chromium-browser/
after_success:
  - ".utility/push-output-to-ghpages.sh"